steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'moreclicks'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/seo-analyzer'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/seo-analyzer'

images:
  - 'gcr.io/$PROJECT_ID/seo-analyzer'

options:
  logging: CLOUD_LOGGING_ONLY
